name       : pkcs11-helper
version    : 1.29.0
release    : 2
source     :
    - https://github.com/OpenSC/pkcs11-helper/releases/download/pkcs11-helper-1.29.0/pkcs11-helper-1.29.0.tar.bz2 : 996846a3c8395e03d8c0515111dc84d82e6e3648d44ba28cb2dbbbca2d4db7d6
license    : GPL-2.0-only
component  : security.library
homepage   : https://github.com/OpenSC/pkcs11-helper
summary    : Library for interacting with PKCS#11 providers
description: |
    Library that simplifies the interaction with PKCS#11 providers for end-user applications using a simple API and optional OpenSSL engine
builddeps  :
    - pkgconfig(nss)
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
