name       : pkcs11-helper
version    : 1.28.0
release    : 1
source     :
    - https://github.com/OpenSC/pkcs11-helper/releases/download/pkcs11-helper-1.28/pkcs11-helper-1.28.0.tar.bz2 : 5bd55adafdbb708e096070dd0a910f23e1d5fd6291922398c1a15f00fff2b5ec
license    : GPL-2.0-only
component  : security.library
homepage   : https://github.com/OpenSC/pkcs11-helper
summary    : Library for interacting with PKCS#11 providers
description: |
    Library that simplifies the interaction with PKCS#11 providers for end-user applications using a simple API and optional OpenSSL engine
builddeps  :
    - pkgconfig(nss)
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
